import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageHeader from "@/components/PageHeader";
import "./globals.css";
import { Suspense } from "react";
import LoadingPage from "./loading";
import { ProductProvider } from "@/context/ProductPageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <div className="shadow-md">
            <PageHeader />
          </div>
          <Suspense fallback={<LoadingPage />}>{children}</Suspense>
        </ProductProvider>
      </body>
    </html>
  );
}
